version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    container_name: app
    volumes:
      - ./:/go
    tty: true
    restart: always
    depends_on:
      - mysql
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: dockerMySQL
    volumes:
      - ./mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ddd_menta
      MYSQL_HOST: dockerMySQL  # 追加!!
      MYSQL_USER: ddd_menta
      MYSQL_PASSWORD: ddd_menta
      MYSQL_ROOT_PASSWORD: ddd_menta
      TZ: Asia/Tokyo
    cap_add:
      - SYS_NICE
    ports:
      - 3306:3306

