@startuml
skinparam packageStyle rectangle

package ユーザー {
  object ユーザー {
    ユーザーID
    名前
    メールアドレス
    パスワード
    自己紹介
  }

  object 経歴 {
    ユーザーID
    西暦from
    西暦to
    詳細
  }
}

ユーザー "1" *-- "0..n" 経歴
note right of ユーザー
名前(必須): 255文字以内
メールアドレス(必須): 255文字以内
パスワード(必須): 12文字以上,英数字それぞれ最低1文字以上
自己紹介(任意): 2000字以内
end note

note right of 経歴
詳細: 1000字以内
西暦from: 1970年以上のint型
西暦to: 1970年以上のint型、西暦fromよりも大きい数字
end note

package ユーザースキル {
  object ユーザースキル {
    タグ名
    評価
    年数
  }
}

package メンタースキル {
  object メンタースキル {
    タグ名
    評価
    年数
  }
}

note bottom of ユーザースキル
タグ名: 30字以内
評価: 1〜5のint型
年数は以下の通り
  ・半年未満
  ・1年未満
  ・3年未満
  ・5年未満
  ・5年以上
end note

package メンター {
  object メンター概要 {
    ユーザーID
    タイトル
    メイン画像
    サブ画像
    カテゴリー
    内容詳細
  }

  object 提供プラン {
    メンター概要ID
    タイトル
    カテゴリー
    内容詳細
    タイプ(単発・月額)
    価格
    承認有無
    ステータス
  }
}

package 提案 {
  object 提案 {
    メンター募集ID
    提案内容
  }
}

note left of 提案
提案内容: 2000文字以内
提案できるのはスキルを5個以上持つユーザのみ
end note

note left of 提供プラン
ステータス
  相談できます(表示され、申込可能)
  今、忙しいです(表示されるが、申込不可)
  表示しない(表示しない、申込不可)
end note

ユーザー "1..n" -- "0..n" ユーザースキル
メンター概要 "1..n" <-- "0..n" メンタースキル
メンター概要 "1" <-- "0..n" 提供プラン
メンター概要 "0..n" --> "1" ユーザー
提案 "0..1" --> "0..n" 提供プラン

package メンティー {
  object メンター募集 {
    タイトル
    予算
    タイプ(単発・月額)
    詳細
    ステータス
  }
}
package プラン申込 {
  object プラン申込 {
    プランID
  }
}
note bottom of メンター募集
・タイトル：255文字以内
・予算：1000円以上の数値
・タイプ：単発か月額か選択可能
・ステータス
  ・下書き・公開・募集終了にすることができる
  ・新規作成時は、下書きまたは公開のみ設定できる
end note
ユーザー "1" <-- "0..n" メンター募集
提供プラン "1" <-- "0..n" プラン申込
提案 "0..n" --> "1" メンター募集

package 契約 {
  object 契約 {
    ステータス
  }
}
note right of 契約
ステータス
  未承認
  契約中
  契約終了
end note
契約 "0..1" --> "1" 提案
契約 "0..1" --> "1" プラン申込

@enduml
